# Generated by Django 5.2.7 on 2025-10-03 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('preciso_melhorar_em', models.TextField(blank=True, null=True)),
                ('coisa_que_me_orgulho', models.TextField(blank=True, null=True)),
                ('gratidao', models.TextField(blank=True, null=True)),
                ('reflexao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada de Diário',
                'verbose_name_plural': 'Entradas de Diário',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PR', 'Principal'), ('SC', 'Secundária')], default='PR', max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrada_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='diario.entradadiario')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
